float:
  any:
  - base_args: ['@metric']
    constructor: DummyAlgo
    disabled: true
    docker_tag: ann-benchmarks-dummy_algo
    module: ann_benchmarks.algorithms.dummy_algo
    name: dummy-algo
    run_groups:
      empty:
        args: []
