float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-flat
      run_groups:
        FLAT:
          args:
            []
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfflat
      run_groups:
        IVFFLAT_32:
          arg_groups: [{ nlist: 32 }]
          query_args: [[1, 4, 8, 16, 32]]
        IVFFLAT_64:
          arg_groups: [{ nlist: 64 }]
          query_args: [[4, 16, 32, 48, 64]]
        IVFFLAT_128:
          arg_groups: [{ nlist: 128 }]
          query_args: [[8, 32, 64, 96, 128]]
        IVFFLAT_512:
          arg_groups: [{ nlist: 512 }]
          query_args: [[32, 128, 256, 384, 512]]
        IVFFLAT_1024:
          arg_groups: [{ nlist: 1024 }]
          query_args: [[64, 256, 512, 768, 1024]]
        IVFFLAT_2048:
          arg_groups: [{ nlist: 2048 }]
          query_args: [[128, 512, 1024, 1536, 2048]]
        IVFFLAT_4096:
          arg_groups: [{ nlist: 4096 }]
          query_args: [[256, 1024, 2048, 3072, 4096]]
        IVFFLAT_8192:
          arg_groups: [{ nlist: 8192 }]
          query_args: [[512, 2048, 4096, 6144, 8192]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFSQ8
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfsq8
      run_groups:
        IVFSQ8:
          args:
            nlist: [128, 256, 512, 1024, 2048, 4096]
          query_args: [[1, 10, 20, 50, 100]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFPQ
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfpq
      run_groups:
        IVFPQ_64:
          args:
            nlist: [64]
            m: [4, 8, 16]
          query_args: [[4, 8, 16, 32, 64]]
        IVFPQ_128:
          args:
            nlist: [128]
            m: [4, 8, 16]
          query_args: [[8, 16, 32, 64, 128]]
        IVFPQ_256:
          args:
            nlist: [256]
            m: [4, 8, 16]
          query_args: [[16, 32, 64, 128, 256]]
        IVFPQ_512:
          args:
            nlist: [512]
            m: [4, 8, 16]
          query_args: [[32, 64, 128, 256, 512]]
        IVFPQ_1024:
          args:
            nlist: [1024]
            m: [4, 8, 16]
          query_args: [[64, 128, 256, 512, 1024]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusHNSW
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-hnsw
      run_groups:
        HNSW:
          args:
            M: [4, 8, 12, 16, 24, 36, 48, 64, 96]
            efConstruction: [200, 500]
          query_args: [[100, 120, 150, 200, 500, 600, 800]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusSCANN
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-scann
      run_groups:
        SCANN:
          args:
            nlist: [64, 128, 256, 512, 1024, 2048, 4096, 8192]
          query_args: [[1, 10, 20, 30, 50]]
